# TP N°1 : Pipeline d'Acquisition de Données (KDD)

**Objectif :** Construire un pipeline capable de fusionner des données hétérogènes (CSV, JSON, SQL) dans un seul DataFrame Pandas.

## 1. Importation des bibliothèques nécessaires

In [1]:
import pandas as pd
import json
from sqlalchemy import create_engine
import requests
from bs4 import BeautifulSoup

## 2. Acquisition des données multi-sources

### 2.1. Données structurées : Fichier CSV

In [4]:
# Chargement du dataset Student Performance (simulé)
df_students = pd.read_csv('../data/student-mat.csv', sep=';')
print("Aperçu des données des étudiants (CSV) :")
display(df_students.head())

Aperçu des données des étudiants (CSV) :

   StudentID school sex  age  G1  G2  G3
0          1     MS   F   19  11  12  13
1          2     MS   M   18  13  14  15
2          3     MS   F   16  15  16  17
3          4     MS   M   17  14  15  16
4          5     MS   F   18  17  18  19

### 2.2. Données semi-structurées : Fichier JSON

In [5]:
# Chargement du dataset de films (simulé)
df_movies = pd.read_json('../data/movies.json')
print("Aperçu des données des films (JSON) :")
display(df_movies.head())

Aperçu des données des films (JSON) :

   MovieID                     Title   Genre  StudentID
0        1              Interstellar  Sci-Fi          1
1        2           The Dark Knight  Action          2
2        3                Fight Club   Crime          3
3        4  The Shawshank Redemption   Drama          4
4        5                      Dune  Sci-Fi          5

### 2.3. Données depuis une base de données (Simulation SQL)

In [6]:
# Pour cet exercice, nous allons simuler l'extraction depuis une base de données.
# Nous allons simplement filtrer le DataFrame des étudiants comme si nous faisions une requête SQL.
df_sql_filtered = df_students[df_students['G3'] > 15].copy()
df_sql_filtered.rename(columns={'G3': 'FinalGrade'}, inplace=True)
print("Aperçu des données filtrées (simulation SQL) :")
display(df_sql_filtered.head())

Aperçu des données filtrées (simulation SQL) :

   StudentID school sex  age  G1  G2  FinalGrade
2          3     MS   F   16  15  16          17
3          4     MS   M   17  14  15          16
4          5     MS   F   18  17  18          19
8          9     MS   F   17  14  15          16
9         10     MS   M   18  15  16          17

### 2.4. Données non-structurées : Web Scraping

In [7]:
# Scraping des titres depuis la page d'accueil de Wikipedia en français
url = 'https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal'
response = requests.get(url)
soup = BeautifulSoup(response.content, 'html.parser')
titles = [h1.text for h1 in soup.find_all('h1')]
df_scraped = pd.DataFrame(titles, columns=['Scraped_Titles'])
print("Titres scrapés depuis Wikipedia :")
display(df_scraped.head())

Titres scrapés depuis Wikipedia :

Empty DataFrame
Columns: [Scraped_Titles]
Index: []

## 3. Fusion des données

In [8]:
# Fusionner les données des étudiants et des films
df_merged = pd.merge(df_students, df_movies, on='StudentID', how='left')
print("Aperçu des données fusionnées (étudiants et films) :")
display(df_merged.head())

Aperçu des données fusionnées (étudiants et films) :

,StudentID,school,sex,age,G1,G2,G3,MovieID,Title,Genre
0,1,MS,F,19,11,12,13,1,Interstellar,Sci-Fi
1,2,MS,M,18,13,14,15,2,The Dark Knight,Action
2,3,MS,F,16,15,16,17,3,Fight Club,Crime
3,4,MS,M,17,14,15,16,4,The Shawshank Redemption,Drama
4,5,MS,F,18,17,18,19,5,Dune,Sci-Fi

## 4. Conclusion
Ce notebook a démontré un pipeline d'acquisition de données simple, en collectant et fusionnant des données de sources variées (CSV, JSON, et simulation SQL) en un seul DataFrame unifié.